# Generated by Django 4.1.2 on 2022-10-08 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.IntegerField()),
                ('date', models.CharField(max_length=128)),
                ('hour', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cpf', models.CharField(max_length=128)),
                ('card', models.CharField(max_length=128)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
            ],
        ),
    ]
