# Generated by Django 4.1.2 on 2022-10-10 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.CharField(max_length=128)),
                ('card', models.CharField(max_length=128)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='Store.store')),
            ],
        ),
    ]
