# Generated by Django 4.1.2 on 2022-10-12 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type_transaction", models.IntegerField()),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                ("value", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=128)),
                ("card", models.CharField(max_length=128)),
                (
                    "operation",
                    models.CharField(
                        choices=[("Entrada", "Entry"), ("Saída", "Out")],
                        default="Entrada",
                        max_length=10,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="Store.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
